### ISSUE TITLE
Provide feedback on correct/incorrect answers

### ISSUE THREAD

**Issue by rchaput** [parmsam/quarto-quiz#3]
Hi,

This is a very nice extension! I'd like to provide feedbacks to my students if they check an incorrect answer to explain why they are mistaken (and ideally for correct answers as well, to give a bit more details), but I'm not familiar with revealjs plugins.

I guess that we could add attributes to spans, e.g., `[Answer which is correct]{.correct explanation="This is correct"}` and `[Incorrect answer]{explanation="No because (...)"}`, and then show them somewhere when an answer is clicked.

If you like this idea and can point me in the right direction, I will try to make a quick PR.

Thanks!

**Comment by parmsam** [comment]
Thanks for the suggestion! The feature was pretty easy to implement, so I just went ahead and added it in.

I've added a [data attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) called `data-explanation` and updated the README. Please try it out and let me know if you have any issues with it.

**Comment by rchaput** [comment]
Nice, thank you for the quick update! I can confirm it works perfectly.

(Plus, because the explanation replaces the "Correct!" / "Incorrect!" label, this opens up the way for Internationalization)

**Comment by parmsam** [comment]
Note that I added defaultCorrect and defaultIncorrect settings you can use to change the change default correct and incorrect messages. The README is updated with how you can use those.
